output = "pkg/storage/database/postgres/model"
pkgname = "model"
wipe     = true
no-tests = true

[psql]
  dbname = "restaurant_assistant"
  host   = "localhost"
  port   = 5432
  user   = "postgres"
  pass   = "postgres"
  sslmode = "disable"
  blacklist = ["goose_db_version"]
